[versions]
kotlin = "2.0.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.9.0" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2024.06.00" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.8.0-beta03" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.7.0" }

[plugins]
android-application = { id = "com.android.application", version = "8.5.0" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
